# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.2'
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-yaml
        types:
          - text
          - yaml
        files: \.(fmf|yaml|yml)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        # Do not install *types-click* - it's not recommended with Click 8 & newer,
        # which is the version a developer encounters given the requirements are not
        # frozen.
        additional_dependencies:
          - click
          - types-Markdown
          - types-requests
          - types-setuptools
          - types-jsonschema
          - types-urllib3
          - ruamel.yaml
          - types-jinja2
        pass_filenames: false
        args: [--config-file=pyproject.toml]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.23.1"
    hooks:
      - id: check-metaschema
        name: "Check JSON schemas validity"
        files: ^tmt/schemas/.*\.yaml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff
        args:
          - '--fix'
          - '--show-fixes'

  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.11.0
    hooks:
      - id: yamlfix
        types:
          - text
        files: \.fmf$
        # Exclude empty .fmf files
        exclude: |
            (?x)^(
                tests/integration/data/nitrate/validation/main.fmf|
                tests/test/select/data/sub/first.fmf|
                tests/test/select/data/sub/second.fmf|
                tests/lint/data/tests/empty/foo/main.fmf
            )$

  - repo: https://github.com/teemtee/tmt.git
    rev: 1.24.1
    hooks:
      - id: tmt-lint
