site_name: tmt
theme:
  name: material
repo_url: https://github.com/teemtee/tmt
site_dir: ../site
docs_dir: .
nav:
  - Home: index.md
  - Overview: overview.md
  - Guide: guide.md
  - Plugins:
    - Overview: plugins/index.md
    - Discover: plugins/discover.md
    - Provision: plugins/provision.md
    - Prepare: plugins/prepare.md
    - Execute: plugins/execute.md
    - Report: plugins/report.md
    - Finish: plugins/finish.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true
