name: test-docs
run-name: Documentation tests

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  doc-test:
    name: Sphinx Documentation Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install hatch
        run: pip install hatch

      - name: Run sphinx html builder
        # -W = warnings as error
        run: hatch run docs:html -W

      - name: Run sphinx linkcheck
        run: hatch run docs:linkcheck
