name: test-docs
run-name: Documentation tests

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  doc-test:
    name: Sphinx Documentation Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Cache Hatch environments
        uses: actions/cache@v3
        with:
          path: .hatch_envs
          key: ${{ runner.os }}-hatch-envs-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-hatch-envs-

      - name: Install hatch
        run: pip install hatch

      - name: Set HATCH_ENV_TYPE_VIRTUAL_PATH
        run: echo "HATCH_ENV_TYPE_VIRTUAL_PATH=$(pwd)/.hatch_envs" >> $GITHUB_ENV

      - name: Run sphinx html builder
        # -W = warnings as error
        run: hatch run docs:html -W

      - name: Run sphinx linkcheck
        run: hatch run docs:linkcheck
